"""Generate analysis/business_analysis.md directly from the exported marts.

Every number in the report is read from clean/ and clean/sql_marts/, so the
write-up cannot drift away from the data (tests/test_pipeline.py checks this).
"""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
CLEAN = ROOT / "clean"
MARTS = CLEAN / "sql_marts"
OUT = ROOT / "analysis" / "business_analysis.md"


def money(x):
    return f"${x:,.0f}"


def build_report() -> str:
    metrics = pd.read_csv(CLEAN / "quality_metrics.csv").set_index("metric")["value"]
    validation = pd.read_csv(CLEAN / "validation_summary.csv").set_index("issue_type")
    reps = pd.read_csv(MARTS / "02_rep_performance.csv")
    monthly = pd.read_csv(MARTS / "03_monthly_pipeline_trend.csv")
    stale = pd.read_csv(MARTS / "05_stale_deal_priority.csv")
    progress = pd.read_csv(MARTS / "06_stage_progression.csv")
    seg = pd.read_csv(MARTS / "07_win_rate_by_segment.csv")
    aged = pd.read_csv(MARTS / "08_open_beyond_longest_cycle.csv").iloc[0]

    top_pipe = reps.sort_values("open_pipeline_value", ascending=False).iloc[0]
    eligible = reps[reps["closed_count"] >= 10]
    top_win = eligible.sort_values("win_rate_pct", ascending=False).iloc[0]
    low_win = eligible.sort_values("win_rate_pct").iloc[0]
    peak_month = monthly.sort_values("opportunity_count", ascending=False).iloc[0]

    ls = seg[seg.dimension == "lead_source"].sort_values("win_rate_pct", ascending=False)
    ls_known = ls[ls.segment != "Unknown"]
    ls_hi, ls_lo = ls_known.iloc[0], ls_known.iloc[-1]
    pr = seg[seg.dimension == "product"].sort_values("win_rate_pct", ascending=False)
    pr_hi, pr_lo = pr.iloc[0], pr.iloc[-1]
    pr_overlap = pr_hi.ci95_low_pct <= pr_lo.ci95_high_pct
    ls_overlap = ls_hi.ci95_low_pct <= ls_lo.ci95_high_pct
    unknown = ls[ls.segment == "Unknown"].iloc[0]

    stale_lines = "\n".join(
        f"- {r.account_name} ({r.rep_name}): {money(r.amount)}, {int(r.days_since_activity)} days since activity"
        for r in stale.head(5).itertuples()
    )
    prog = {(r.from_stage, r.to_stage): r.progressed_to_date_pct for r in progress.itertuples()}

    return f"""# CRM Pipeline Analysis

## Scope and caveat

This report is generated by `build_analysis.py` from the exported marts. It uses the
synthetic CRM dataset as of 2026-09-01. Findings are descriptive operational
observations, not causal claims or a forecast. Lead-source, product, and team effects
are planted simulation parameters, so they demonstrate the analysis workflow and are
not real-world evidence.

## Findings

### 1. Most open pipeline is older than any deal has ever taken to close

The longest closed sales cycle in the data is {int(aged.longest_closed_cycle_days)} days. Yet
{int(aged.open_beyond_cycle)} of {int(aged.total_open_opportunities)} open opportunities ({aged.open_beyond_cycle_pct}%) are
older than that, representing {money(aged.value_beyond_cycle)}. {int(aged.beyond_cycle_but_not_stale)} of them are
not flagged by the 30-day stale rule because they still log activity, so activity-based
staleness alone misses them. These deals need a close-out decision.

### 2. Stale follow-up should be value-prioritized

{int(metrics['Stale Opportunities'])} open opportunities have had no activity for more than 30 days,
worth {money(metrics['Stale Pipeline Value'])} ({metrics['Stale Value Pct Of Open Pipeline']}% of open pipeline value).
The queue is ranked by the heuristic `amount * days_since_activity` (not a recovery
probability). Top five:

{stale_lines}

### 3. Rep results need volume context

{top_pipe.rep_name} has the largest open pipeline at {money(top_pipe.open_pipeline_value)}
({top_pipe.win_rate_pct}% win rate on {int(top_pipe.closed_count)} closed deals). Among reps with at least
10 closed deals, win rates range from {low_win.win_rate_pct}% ({low_win.rep_name}, n={int(low_win.closed_count)}) to
{top_win.win_rate_pct}% ({top_win.rep_name}, n={int(top_win.closed_count)}). With samples this small, treat the
spread as a review signal, not a performance ranking.

### 4. Opportunity creation peaked in {pd.to_datetime(peak_month.created_month).strftime('%B %Y')}

{int(peak_month.opportunity_count)} opportunities were created that month. One synthetic period does not
establish seasonality.

### 5. Win-rate segments (95% Wilson intervals)

- Lead source: {ls_hi.segment} wins {ls_hi.win_rate_pct}% ({ls_hi.ci95_low_pct}-{ls_hi.ci95_high_pct}%, n={int(ls_hi.closed_deals)}) versus
  {ls_lo.segment} {ls_lo.win_rate_pct}% ({ls_lo.ci95_low_pct}-{ls_lo.ci95_high_pct}%, n={int(ls_lo.closed_deals)}). The intervals
  {'overlap, so the gap is not distinguishable from noise' if ls_overlap else 'do not overlap, so the gap is larger than sampling noise (in this simulation)'}.
- Product: {pr_hi.segment} {pr_hi.win_rate_pct}% versus {pr_lo.segment} {pr_lo.win_rate_pct}%. The intervals
  {'overlap, so this gap is not statistically distinguishable at this sample size' if pr_overlap else 'do not overlap'}.
- Opportunities with no lead source win only {unknown.win_rate_pct}% (n={int(unknown.closed_deals)}) and make up
  {int(metrics['Missing Lead Source Opportunities'])} of 900 records, so missing lead source is also a data-quality issue.

### 6. Stage progression to date

{prog[('Prospecting','Qualification')]}% of opportunities reached Qualification, {prog[('Qualification','Proposal')]}% of those reached Proposal,
and {prog[('Proposal','Negotiation')]}% of those reached Negotiation. From Negotiation, {prog[('Negotiation','Closed Won')]}% closed won and
{prog[('Negotiation','Closed Lost')]}% closed lost. These are progressed-to-date rates: open deals that have not moved yet
count as not progressed, so later-stage rates are understated until those deals resolve.

## Data quality status

| Rule | Count | Status |
|---|---:|---|
| Invalid or missing amount | {int(validation.loc['invalid_amount','issue_count'])} | {validation.loc['invalid_amount','status']} |
| Missing lead source | {int(validation.loc['missing_lead_source','issue_count'])} | {validation.loc['missing_lead_source','status']} |
| Missing DUNS number | {int(validation.loc['missing_duns','issue_count'])} | {validation.loc['missing_duns','status']} |
| All other rules (7) | 0 | PASS |

## Recommended operating actions

1. Run a weekly close-out review of the {int(aged.open_beyond_cycle)} opportunities older than {int(aged.longest_closed_cycle_days)} days, highest value first.
2. Work the stale queue top-down, and require a status confirmation before counting any of it as recoverable.
3. Review reps with closed-deal volume, pipeline mix, and deal age together. Do not rank on win rate alone.
4. Make lead source a required field. Resolve the {int(validation.loc['invalid_amount','issue_count'])} amount issues and {int(validation.loc['missing_duns','issue_count'])} missing DUNS records through CRM hygiene workflows.
5. Report pipeline with and without imputed amounts ({money(metrics['Open Pipeline Value'])} vs {money(metrics['Open Pipeline Value Excluding Imputed'])}).
"""


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_report(), encoding="utf-8")
    print(OUT.relative_to(ROOT))
